# Generated by Django 5.2 on 2025-12-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title_ru')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title_en')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(verbose_name='Description_ru')),
                ('description_en', models.TextField(verbose_name='Description_en')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Elonlar',
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title_ru')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title_en')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(verbose_name='Description_ru')),
                ('description_en', models.TextField(verbose_name='Description_en')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Yunalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=20, verbose_name='Title_ru')),
                ('title_en', models.CharField(max_length=20, verbose_name='Title_en')),
                ('description', models.TextField(max_length=240, verbose_name='Description')),
                ('description_ru', models.TextField(max_length=240, verbose_name='Description_ru')),
                ('description_en', models.TextField(max_length=240, verbose_name='Description_en')),
                ('image', models.ImageField(upload_to='yunalishlar/')),
                ('kurs', models.CharField(choices=[('9-sinf', '9-sinf'), ('11-sinf', '11-sinf')], default={'9-sinf': '9-sinf'}, verbose_name='Kurs')),
                ('kurs_ru', models.CharField(choices=[('9-х классов', '9-х классов'), ('11-х классов', '11-х классов')], default={'9-х классов': '9-х классов'}, verbose_name='Kurs')),
                ('kurs_en', models.CharField(choices=[('9th grade', '9th grade'), ('11th grade', '11th grade')], default={'9th grade': '9th grade'}, verbose_name='Kurs')),
                ('shakl', models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Dual', 'Dual')], default={'Kunduzgi': 'Kunduzgi'}, verbose_name='Shakl')),
                ('shakl_ru', models.CharField(choices=[('Очную', 'Очную'), ('Дуальную', 'Дуальную')], default={'Очную': 'Очную'}, verbose_name='Shakl')),
                ('shakl_en', models.CharField(choices=[('Daytime', 'Daytime'), ('Dual', 'Dual')], default={'Daytime': 'Daytime'}, verbose_name='Shakl')),
            ],
            options={
                'verbose_name_plural': 'Yunalishlar',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('elonlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mainapp.elonlar')),
                ('yangiliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mainapp.yangiliklar')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
    ]
